# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd7644048e436418403d4f6c94186a49bb483dae8ba85ddafed7f438ad1dda0565e0a771f4e3d2149a77fd0947c8ab4fc24992093a8c2d15c715658ad5860f03

test:
  secret_key_base: efb7b171592227f8010c0412dc829cdb90a1c46c4092391af2aa6d17d0e547003577726e04348d41ef7f928f8b084e2b097ef08f178128562f43d87a6e89b993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
